[package]
name = "create_shortcut"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.52", features = [
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_Foundation"
] }