[package]
name = "icon_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
image = "0.25"
file_icon_provider = "0.4"


[[bin]]
name = "file_to_image"
path = "src/file_to_image.rs"